server:
  port: 3000

spring:
  application:
    name: Teryaq
  datasource:
    url: jdbc:postgresql://localhost:5432/teryaq
    username: postgres
    password: raneem2003
    driver-class-name: org.postgresql.Driver
    name: teryaq
  flyway:
    enabled: true
    locations: classpath:/db/migration # This is the default path Flyway looks in
    # If your database already has existing tables not managed by Flyway before,
    # this will create the Flyway history table without running existing scripts.
    # New scripts will then be applied.
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      format_sql: true
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    show-sql: true



jwtKey: 7402bb3c24c35f15d1a7f1422078d9c1a4d9ebf1a276ff01ac84e6407625532e