server:
  port: 3000

spring:
  management:
    endpoints:
      web:
        exposure:
          include=*:
  application:
    name: Teryaq
  datasource:
    url: jdbc:postgresql://localhost:5432/teryaq
    username: postgres
    password: raneem2003
    driver-class-name: org.postgresql.Driver
    name: teryaq
  flyway:
    enabled: true
    locations: classpath:/db/migration # This is the default path Flyway looks in
    # If your database already has existing tables not managed by Flyway before,
    # this will create the Flyway history table without running existing scripts.
    # New scripts will then be applied.
    baseline-on-migrate: true
    baseline-version: 8
    validate-on-migrate: true
#    init-sql: SET search_path TO public;
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    open-in-view: true
    properties:
      format_sql: true
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        enable_lazy_load_no_trans: true
    show-sql: true




jwtKey: 7402bb3c24c35f15d1a7f1422078d9c1a4d9ebf1a276ff01ac84e6407625532e